version: '3.6'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static:/data/static
      - media:/data/media

  postgres:
    build: ./compose/postgres
    env_file:
      - .env.local
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  redis:
    build: ./compose/redis

  celeryworker:
    <<: *django
    image: django_packages_dev_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    image: django_packages_dev_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat.sh

  flower:
    <<: *django
    image: django_packages_dev_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower.sh

volumes:
  postgres_backup_dev: {}
  postgres_data_dev: {}
  media: {}
  static: {}
